"""initial

Revision ID: 4b5cc48fddce
Revises: 
Create Date: 2026-06-09 19:09:22.047192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b5cc48fddce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lots',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('tag_number', sa.String(length=100), nullable=False),
    sa.Column('breed', sa.Enum('ANGUS', 'HEREFORD', 'BRAHMAN', 'LIMOUSIN', 'SHORTHORN', 'CRIOLLO', name='breed'), nullable=False),
    sa.Column('category', sa.Enum('CALF', 'STEER', 'COW', 'BULL', 'HEIFER', name='animal_category'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEAD', 'SOLD', name='animal_status'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('current_lot_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_number')
    )
    op.create_index('idx_animals_current_lot', 'animals', ['current_lot_id'], unique=False, postgresql_where=sa.text("deleted = false AND status = 'ACTIVE'"))
    op.create_table('animal_lot_periods',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_animal_lot_periods_by_animal', 'animal_lot_periods', ['animal_id', 'entered_at'], unique=False)
    op.create_index('idx_animal_lot_periods_by_lot', 'animal_lot_periods', ['lot_id', 'entered_at', 'exited_at'], unique=False)
    op.create_index('idx_animal_lot_periods_single_open', 'animal_lot_periods', ['animal_id'], unique=True, postgresql_where=sa.text('exited_at IS NULL'))
    op.create_table('events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('BIRTH', 'MOVE', 'DEATH', 'SALE', 'RECLASSIFICATION', 'WEIGHT', 'VACCINATION', name='event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("type != 'MOVE' OR (jsonb_exists(payload,'from_lot_id') AND jsonb_exists(payload,'to_lot_id'))", name='chk_events_move'),
    sa.CheckConstraint("type != 'RECLASSIFICATION' OR jsonb_exists(payload,'new_category')", name='chk_events_reclassification'),
    sa.CheckConstraint("type != 'VACCINATION' OR jsonb_exists(payload,'vaccine_name')", name='chk_events_vaccination'),
    sa.CheckConstraint("type != 'WEIGHT' OR jsonb_exists(payload,'weight_kg')", name='chk_events_weight'),
    sa.CheckConstraint("type IN ('BIRTH','MOVE','DEATH','SALE','RECLASSIFICATION','WEIGHT','VACCINATION')", name='chk_events_type'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_by_animal', 'events', ['animal_id', 'occurred_at'], unique=False)
    op.create_index('idx_events_move', 'events', ['animal_id'], unique=False, postgresql_where=sa.text("type = 'MOVE'"))
    op.create_index('idx_events_vaccination', 'events', ['animal_id'], unique=False, postgresql_where=sa.text("type = 'VACCINATION'"))
    op.create_index('idx_events_weight', 'events', [sa.literal_column("CAST(payload->>'weight_kg' AS numeric)")], unique=False, postgresql_where=sa.text("type = 'WEIGHT'"))
    op.create_index('idx_events_weight_adg', 'events', ['animal_id', 'occurred_at'], unique=False, postgresql_where=sa.text("type = 'WEIGHT'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_weight_adg', table_name='events', postgresql_where=sa.text("type = 'WEIGHT'"))
    op.drop_index('idx_events_weight', table_name='events', postgresql_where=sa.text("type = 'WEIGHT'"))
    op.drop_index('idx_events_vaccination', table_name='events', postgresql_where=sa.text("type = 'VACCINATION'"))
    op.drop_index('idx_events_move', table_name='events', postgresql_where=sa.text("type = 'MOVE'"))
    op.drop_index('idx_events_by_animal', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_animal_lot_periods_single_open', table_name='animal_lot_periods', postgresql_where=sa.text('exited_at IS NULL'))
    op.drop_index('idx_animal_lot_periods_by_lot', table_name='animal_lot_periods')
    op.drop_index('idx_animal_lot_periods_by_animal', table_name='animal_lot_periods')
    op.drop_table('animal_lot_periods')
    op.drop_index('idx_animals_current_lot', table_name='animals', postgresql_where=sa.text("deleted = false AND status = 'ACTIVE'"))
    op.drop_table('animals')
    op.drop_table('lots')
    op.drop_table('fields')
    # ### end Alembic commands ###
